//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.08 at 04:15:27 ���� CST 
//


package com.hualife.foundation.component.cache.config.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="listenerType" use="required" type="{http://www.hualife.com/foundation/component/cache}listener-type" />
 *       &lt;attribute name="impl" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="syn" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "cacheListener")
public class CacheListener {

    @XmlAttribute(required = true)
    protected ListenerType listenerType;
    @XmlAttribute(required = true)
    protected String impl;
    @XmlAttribute
    protected Boolean syn;

    /**
     * Gets the value of the listenerType property.
     * 
     * @return
     *     possible object is
     *     {@link ListenerType }
     *     
     */
    public ListenerType getListenerType() {
        return listenerType;
    }

    /**
     * Sets the value of the listenerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListenerType }
     *     
     */
    public void setListenerType(ListenerType value) {
        this.listenerType = value;
    }

    /**
     * Gets the value of the impl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImpl() {
        return impl;
    }

    /**
     * Sets the value of the impl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImpl(String value) {
        this.impl = value;
    }

    /**
     * Gets the value of the syn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSyn() {
        if (syn == null) {
            return true;
        } else {
            return syn;
        }
    }

    /**
     * Sets the value of the syn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSyn(Boolean value) {
        this.syn = value;
    }

}
