//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.08 at 04:15:27 ���� CST 
//


package com.hualife.foundation.component.cache.config.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hualife.com/foundation/component/cache}cacheListeners" minOccurs="0"/>
 *         &lt;element ref="{http://www.hualife.com/foundation/component/cache}expiry" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.hualife.com/foundation/component/cache}cacheLoader"/>
 *           &lt;element ref="{http://www.hualife.com/foundation/component/cache}cacheWriter"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="provider" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="serializeType" type="{http://www.hualife.com/foundation/component/cache}serialize-type" />
 *       &lt;attribute name="restartWithClearData" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="transactionEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="statisticsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cacheListeners",
    "expiry",
    "cacheLoader",
    "cacheWriter"
})
@XmlRootElement(name = "cache")
public class Cache {

    protected CacheListeners cacheListeners;
    protected Expiry expiry;
    protected CacheLoader cacheLoader;
    protected CacheWriter cacheWriter;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected String provider;
    @XmlAttribute
    protected SerializeType serializeType;
    @XmlAttribute
    protected Boolean restartWithClearData;
    @XmlAttribute
    protected Boolean transactionEnabled;
    @XmlAttribute
    protected Boolean statisticsEnabled;

    /**
     * Gets the value of the cacheListeners property.
     * 
     * @return
     *     possible object is
     *     {@link CacheListeners }
     *     
     */
    public CacheListeners getCacheListeners() {
        return cacheListeners;
    }

    /**
     * Sets the value of the cacheListeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link CacheListeners }
     *     
     */
    public void setCacheListeners(CacheListeners value) {
        this.cacheListeners = value;
    }

    /**
     * Gets the value of the expiry property.
     * 
     * @return
     *     possible object is
     *     {@link Expiry }
     *     
     */
    public Expiry getExpiry() {
        return expiry;
    }

    /**
     * Sets the value of the expiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expiry }
     *     
     */
    public void setExpiry(Expiry value) {
        this.expiry = value;
    }

    /**
     * Gets the value of the cacheLoader property.
     * 
     * @return
     *     possible object is
     *     {@link CacheLoader }
     *     
     */
    public CacheLoader getCacheLoader() {
        return cacheLoader;
    }

    /**
     * Sets the value of the cacheLoader property.
     * 
     * @param value
     *     allowed object is
     *     {@link CacheLoader }
     *     
     */
    public void setCacheLoader(CacheLoader value) {
        this.cacheLoader = value;
    }

    /**
     * Gets the value of the cacheWriter property.
     * 
     * @return
     *     possible object is
     *     {@link CacheWriter }
     *     
     */
    public CacheWriter getCacheWriter() {
        return cacheWriter;
    }

    /**
     * Sets the value of the cacheWriter property.
     * 
     * @param value
     *     allowed object is
     *     {@link CacheWriter }
     *     
     */
    public void setCacheWriter(CacheWriter value) {
        this.cacheWriter = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvider(String value) {
        this.provider = value;
    }

    /**
     * Gets the value of the serializeType property.
     * 
     * @return
     *     possible object is
     *     {@link SerializeType }
     *     
     */
    public SerializeType getSerializeType() {
        return serializeType;
    }

    /**
     * Sets the value of the serializeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SerializeType }
     *     
     */
    public void setSerializeType(SerializeType value) {
        this.serializeType = value;
    }

    /**
     * Gets the value of the restartWithClearData property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRestartWithClearData() {
        if (restartWithClearData == null) {
            return false;
        } else {
            return restartWithClearData;
        }
    }

    /**
     * Sets the value of the restartWithClearData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRestartWithClearData(Boolean value) {
        this.restartWithClearData = value;
    }

    /**
     * Gets the value of the transactionEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTransactionEnabled() {
        if (transactionEnabled == null) {
            return false;
        } else {
            return transactionEnabled;
        }
    }

    /**
     * Sets the value of the transactionEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTransactionEnabled(Boolean value) {
        this.transactionEnabled = value;
    }

    /**
     * Gets the value of the statisticsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isStatisticsEnabled() {
        if (statisticsEnabled == null) {
            return false;
        } else {
            return statisticsEnabled;
        }
    }

    /**
     * Sets the value of the statisticsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStatisticsEnabled(Boolean value) {
        this.statisticsEnabled = value;
    }

}
