//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.25 at 11:13:31 ���� CST 
//


package com.hualife.foundation.component.cache.config.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expiry-time-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="expiry-time-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="periodsOfTime"/>
 *     &lt;enumeration value="pointInTime"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "expiry-time-type")
@XmlEnum
public enum ExpiryTimeType {

    @XmlEnumValue("periodsOfTime")
    PERIODS_OF_TIME("periodsOfTime"),
    @XmlEnumValue("pointInTime")
    POINT_IN_TIME("pointInTime");
    private final String value;

    ExpiryTimeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExpiryTimeType fromValue(String v) {
        for (ExpiryTimeType c: ExpiryTimeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
