//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.08 at 04:15:27 ���� CST 
//


package com.hualife.foundation.component.cache.config.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for listener-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="listener-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CREATED"/>
 *     &lt;enumeration value="EXPIRY"/>
 *     &lt;enumeration value="READ"/>
 *     &lt;enumeration value="REMOVED"/>
 *     &lt;enumeration value="UPDATED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "listener-type")
@XmlEnum
public enum ListenerType {

    CREATED,
    EXPIRY,
    READ,
    REMOVED,
    UPDATED;

    public String value() {
        return name();
    }

    public static ListenerType fromValue(String v) {
        return valueOf(v);
    }

}
