//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.08 at 04:15:27 ���� CST 
//


package com.hualife.foundation.component.cache.config.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hualife.foundation.component.cache package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Notify_QNAME = new QName("http://www.hualife.com/foundation/component/cache", "notify");
    private final static QName _Syn_QNAME = new QName("http://www.hualife.com/foundation/component/cache", "syn");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hualife.foundation.component.cache
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CacheListener }
     * 
     */
    public CacheListener createCacheListener() {
        return new CacheListener();
    }

    /**
     * Create an instance of {@link Cache }
     * 
     */
    public Cache createCache() {
        return new Cache();
    }

    /**
     * Create an instance of {@link CacheListeners }
     * 
     */
    public CacheListeners createCacheListeners() {
        return new CacheListeners();
    }

    /**
     * Create an instance of {@link CacheLoader }
     * 
     */
    public CacheLoader createCacheLoader() {
        return new CacheLoader();
    }

    /**
     * Create an instance of {@link Caches }
     * 
     */
    public Caches createCaches() {
        return new Caches();
    }

    /**
     * Create an instance of {@link ExtProperties }
     * 
     */
    public ExtProperties createExtProperties() {
        return new ExtProperties();
    }

    /**
     * Create an instance of {@link Expiry }
     * 
     */
    public Expiry createExpiry() {
        return new Expiry();
    }

    /**
     * Create an instance of {@link Asyn }
     * 
     */
    public Asyn createAsyn() {
        return new Asyn();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link CacheWriter }
     * 
     */
    public CacheWriter createCacheWriter() {
        return new CacheWriter();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hualife.com/foundation/component/cache", name = "notify")
    public JAXBElement<Boolean> createNotify(Boolean value) {
        return new JAXBElement<Boolean>(_Notify_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hualife.com/foundation/component/cache", name = "syn")
    public JAXBElement<Boolean> createSyn(Boolean value) {
        return new JAXBElement<Boolean>(_Syn_QNAME, Boolean.class, null, value);
    }

}
