//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.08 at 04:15:27 ���� CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hualife.com/foundation/component/cache", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hualife.foundation.component.cache.config.model;
